[dependencies]
base = "0.7.3"
encoding = "https://github.com/aviate-labs/encoding.mo#v0.3.2"
fmt = "https://github.com/aviate-labs/fmt.mo#v0.1.0"
Itertools = "https://github.com/NatLabs/Itertools#v0.1.0"